config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  resources :friend_requests, only: [:index, :create, :update, :destroy]
  resources :friendships
  resources :friends, only: [:index, :destroy]
  resources :likes, only:[ :create, :destroy]
  resources :users
  resources :posts do
    resources :comments
  end
    

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include Gravtastic
  gravtastic
        
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  
  after_create :send_welcome_email

  


  def active_friends
    friends.select{ |friend| friend.friends.include?(self) }  
  end
  
  def pending_friends
    friends.select{ |friend| !friend.friends.include?(self) }  
  end

  def remove_friend(friend)
    friendship = friendships.find_by(friend: friend)
    friendship.destroy
  end

  def friend?(user)
    friends.include?(user)
  end

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.birthday = auth.info.birthday
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.search(search)
    if search
      where('lower(first_name) LIKE ? OR lower(last_name) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%")
    else
      all
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :facebook

 
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def delete 
    @user = current_user
    redirect_to root_path
    @user.destroy
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index 
        @incoming = FriendRequest.where(friend: current_user)
        @outgoing = current_user.friend_requests

        if params[:search]
            @users = User.search(params[:search]).order("created_at DESC")
        else
            @users = User.all.order("created_at DESC")
        end
    end

    def show
        @user = User.find(params[:id])
        @posts = @user.posts.order("created_at DESC")
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
             # Tell the UserMailer to send a welcome email after save
            redirect_to users_path
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to users_path
        else
            render :edit
        end
    end

    def destroy
        redirect_to root_path
        @user = User.find(params[:id])
        @user.destroy
    end

    private

    
     def user_params
        params.require(:user).permit(:name, :email, :password)
     end

     def search_params
        params.permit(:search)
     end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/index.html.erb
<div class="container mt-5">


<% if params[:search].present? %>
  <% if @users.blank? %>
    No Results
  <% elsif %>
    <h2 class="text-center fs-3 py-4"> Your Search Results </h2>
    <% @users.each do |user| %>
     <div class="d-flex mx-auto align-items-center mt-3 justify-content-start w-50">
      <%= image_tag user.gravatar_url(:rating => 'R', :secure => true, :size => 80), class:"rounded-circle" %>
    <%= link_to "#{user.first_name} #{user.last_name}", user_path(user), class:"text-decoration-none mx-4"%> 
    </div>
    <% end %>
  <% end %>
<% else %>
<h2 class="title fs-3 py-4 text-center"> Discover People </h2>
<% @users.each do |user| %>
    <%  if current_user.id != user.id && user.friends.exclude?(current_user)%>
      <div class="d-flex mx-auto align-items-center mt-3 justify-content-between w-50">
        <%= image_tag user.gravatar_url(:rating => 'R', :secure => true, :size => 80), class:"rounded-circle" %>
        <%= link_to "#{user.first_name} #{user.last_name}", user_path(user), class:"text-decoration-none" %> 
        <% if current_user.friend_requests.exists?(friend_id: user.id) %>
            <%= button_to "Cancel Friend Request", friend_request_path(current_user.friend_requests.where(friend_id: user.id).first), method: :delete, class:"btn btn-primary" %>
        <% elsif user.friend_requests.exists?(friend_id: current_user.id) %>
          <div class="d-flex">
            <%= button_to "Accept", friend_request_path(user.friend_requests.where(friend_id: current_user.id).first), method: :put, class:"btn btn-success" %>
            <%= button_to "Reject", friend_request_path(user.friend_requests.where(friend_id: current_user.id).first), method: :delete, class:"btn btn-danger mx-3" %>
          </div>
        <% else %>
            <%= button_to "Add Friend", friend_requests_path(friend_id: user.id), method: :post, class:"btn btn-primary mx-4" %>  
        <% end %>
      </div>
    <%end%>
<% end %>
<% end %>

</div>

app/views/users/show.html.erb
<div class="container text-center">
  <div class="d-flex flex-row align-items-center">
    <%= image_tag @user.gravatar_url(:rating => 'R', :secure => true, :size => 90), class:"rounded-circle" %>
    <div class="d-flex flex-column mx-5">
    <%= link_to "#{@user.first_name} #{@user.last_name}", user_path(@user), class:"text-decoration-none fs-4 " %>
    <%= @user.location %> <br>
    <% if @user.birthday %>
      <%= @user.birthday.strftime("%B %d, %Y") %>
    <% end %> <br>
    <%= "Friends: #{@user.friends.count}" %> <br>
    <%= "Posts: #{@user.posts.count}" %> <br>
    <div>
      <% unless @user == current_user %>
        <% if current_user.friends.include?(@user) %>
          <%= button_to "Unfriend", friendship_path(@user), method: :delete, class:"btn btn-secondary" %>
        <% elsif @user.friend_requests.exists?(friend_id: current_user.id) %>
          <%= button_to "Accept Friend Request", friendship_path(@user), method: :patch, class:"btn btn-success" %>
          <%= button_to "Reject Friend Request", friendship_path(@user), method: :delete, class:"btn btn-danger" %>
        <% elsif current_user.friend_requests.exists?(friend_id: @user.id) %>
          <%= button_to "Cancel Friend Request", friendship_path(@user), method: :delete, class:"btn btn-secondary" %>
        <% else %>
          <%= button_to "Add Friend", friend_requests_path(friend_id: @user.id), method: :post, class:"btn btn-primary" %>
        <% end %>
      <% end %>
    </div>
  </div>



  <div id="posts" class="flex-fill">
    <% if @posts %>
    <% @posts.each do |post| %>
    <div class="d-flex justify-content-center flex-fill">
      <div class="d-flex w-50 my-4 border rounded justify-content-around rounded-50 p-4">
        <div>
          <%= image_tag post.user.gravatar_url(:rating => 'R', :secure => true, :size => 50), class:"rounded-circle" %>
          <%= link_to "#{post.user.first_name} #{post.user.last_name}", user_path(post.user), class:"text-decoration-none mx-2" %>
        </div>
        <div class="w-25 mx-4 flex-fill">
          <%= render post %>  
          <div class="d-flex align-items-center">

            <%= post.likes.count %>
            <%= render partial: "layouts/likes_button", locals: { likable: post } %>
            <div class="mx-2">
              <%= post.comments.count %>
              <i class="fa-regular fa-comment mx-3"></i>
            </div>
          </div>
          <%= link_to "Show this post", post %>
        </div>
        <% if post.user == current_user %>
          <%= link_to edit_post_path(post), class:"btn btn-floating mx-1" do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
          <%= button_to post, method: :delete, class:"btn btn-floating mx-1" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>   
        <% end %>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>