config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  resources :friend_requests, only: [:index, :create, :update, :destroy]
  resources :friendships
  resources :friends, only: [:index, :destroy]
  resources :likes, only:[ :create, :destroy]
  resources :users
  resources :posts do
    resources :comments
  end
    

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  validate :not_self
  validate :not_pending 
  
  belongs_to :user
  belongs_to :friend, class_name: "User"
  

  def accept 
    user.friends << friend
    destroy
  end

  private

  def not_self
    errors.add(:friend, "can't be the same as the user") if user == friend
  end

  def not_pending
    errors.add(:friend, "is already a friend") if user.friends.include?(friend)
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
    before_action :set_friend_request, except: [:index, :create]
    def index
        @incoming = FriendRequest.where(friend: current_user)
        @outgoing = current_user.friend_requests
    end

    def create
        friend = User.find(params[:friend_id])
        @friend_request = current_user.friend_requests.new(friend: friend)

        if @friend_request.save
            flash[:notice] = "Friend request sent."
            redirect_to users_path
            # render :show, status: :created, location: @friend_request
        else
            flash[:error] = "Unable to send friend request."
            render json: @friend_request.errors, status: :unprocessable_entity
        end
    end

    def update
        @friend_request.accept
        head :no_content
    end


    def destroy
        @friend_request.destroy
        redirect_to users_path
    end

    private

    def set_friend_request
        @friend_request = FriendRequest.find(params[:id])
    end


end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/index.html.erb
<div class="text-center">
  <p class="fs-4 mx-3 my-4"> You have <%= @incoming.count%> friend requests</p>
  <% if @incoming %>
    <% @incoming.each do |friend_request| %>
      <div class="d-flex justify-content-center align-items-center">
        <%= image_tag friend_request.user.gravatar_url(:rating => 'R', :secure => true, :size => 50), class:"rounded-circle mx-3" %>
        <%= link_to "#{friend_request.user.first_name} #{friend_request.user.last_name}", user_path(friend_request.user), class:"text-decoration-none mx-3" %>
        <%= button_to "Accept", friend_request_path(friend_request), method: :put, class:"btn btn-success mx-3" %>
        <%= button_to "Reject", friend_request_path(friend_request), method: :delete, class:"btn btn-danger mx-3" %>
      </div>
    <%end%>
  <%end%>

  <p class="fs-4 mx-3 my-4"> You have <%= current_user.friends.count%> friends</p>
  <% if @current_user.friends %>
    <% @current_user.friends.each do |friend| %>
      <div class="d-flex justify-content-center">
        <%= image_tag friend.gravatar_url(:rating => 'R', :secure => true, :size => 50), class:"rounded-circle mx-3" %>
        <%= link_to friend.first_name + " " + friend.last_name, user_path(friend), class:"text-decoration-none mx-2" %>
        <%= button_to "Unfriend", friend_path(friend), method: :delete, class:"btn btn-secondary mx-1" %>
      </div>
    <% end %>
  <% end %>
</div>