config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  resources :friend_requests, only: [:index, :create, :update, :destroy]
  resources :friendships
  resources :friends, only: [:index, :destroy]
  resources :likes, only:[ :create, :destroy]
  resources :users
  resources :posts do
    resources :comments
  end
    

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/_likes_button.html.erb
<% like = current_user.likes.find_by(likable: likable) %>
<% if like %>
  <%= button_to like_path(like), method: :delete, class:"btn btn-floating mx-1" do%>
    <i class="far fa-thumbs-down"></i>
  <% end %>
<% else %>
    <%= button_to likes_path(like: { likable_id: likable.id, likable_type: likable.class.to_s }), method: :post, class:"btn btn-floating mx-1" do %>
      <i class="far fa-thumbs-up"></i>
    <% end %>   

<% end %>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "OdinBook", root_path, class:"navbar-brand" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_user%>
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active"  %> 
        </li>
        <li class="nav-item">
          <%= link_to "Discover", users_path, class:"nav-link active"  %> 
        </li>
        <li class="nav-item">
           <%= link_to "My profile", user_path(current_user), class:"nav-link active"  %>
        </li>
      <%end%>
      </ul>      

        <% if current_user %>
          <div class="d-flex">
            <%= link_to friend_requests_path , class:"btn btn-primary position-relative" do %> 
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                  <% if FriendRequest.where(friend: current_user) %>
                    <%= FriendRequest.where(friend: current_user).count %>
                  <%else%>
                    0
                  <%end%>
                <span class="visually-hidden">friend requests</span>
                </span>
              <i class="fa-solid fa-user-group">
              </i>
            <% end %>
          </div>

        <div class="d-flex flex-row">
          <%= form_tag(users_path, method: 'get', class: 'rounded input-group mx-4') do %>
            <%= text_field_tag :search, params[:search], class:'form-control rounded',placeholder: "Search for users" %> 
            <%= button_tag(type: "submit", class: "btn btn-default input-group-text border-0") do %>
                <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        
          <div class="d-flex align-items-center" type="submit">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-link px-3 me-2 text-decoration-none" %>
          </div>
        </div>

        <% else %>
          <div class="d-flex align-items-center">
              <%= link_to "Login", new_user_session_path, class:"btn btn-link px-3 me-2 text-decoration-none" %>
              <%= link_to "Sign up", new_user_registration_path, class:"btn btn-primary me-3" %>
          </div>
        <% end %>       
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="/fonts/fontawesome-free-5.3.1-web/css/all.css">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render "layouts/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>